Models/Book.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ChooseBookApp.Models
{
    public class Book
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Author { get; set; }
        public string ShortDescription { get; set; }
        public string Description { get; set; }
        public int Pages { get; set; }
        public string ImageUrl { get; set; }
        public int CategoryId{ get; set; }
    }
}

Models/BookCategoryModel.cs
using System.Collections.Generic;

namespace ChooseBookApp.Models
{
    public class BookCategoryModel
    {
        public Book Book { get; set; }
        public IEnumerable<Book> Books { get; set; }

        public IEnumerable<Category> Categories { get; set; }
    }
}

Models/Category.cs
namespace ChooseBookApp.Models
{
    public class Category
    {
     public int Id { get; set; }   

     public string Name { get; set; }
    }
}

Models/ErrorViewModel.cs
using System;

namespace ChooseBookApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Repository.cs
using System.Collections.Generic;
using System.Linq;

namespace ChooseBookApp.Models
{
    public static class Repository
    {
        private static List<Book> _books = null;

        static Repository() {
            _books = new List<Book>() {
                new Book() {
                    Id = 0,
                    Name = "It",
                    Author = "Stephen King",
                    Description = "It is a 1986 horror novel by American author Stephen King. It was his 22nd book and his 17th novel written under his own name. The story follows the experiences of seven children as they are terrorized by an evil entity that exploits the fears of its victims to disguise itself while hunting its prey. ",
                    Pages = 1138,
                    ImageUrl = "1.jpg"

                },
                new Book() {
                    Id = 1,
                    Name = "The Stand",
                    Author = "Stephen King",
                    Description = "The Stand is a post-apocalyptic dark fantasy novel written by American author Stephen King and first published in 1978 by Doubleday. The plot centers on a deadly pandemic of weaponized influenza and its aftermath, in which the few surviving humans gather into factions that are each led by a personification of either good or evil. King started writing the story in February 1975",
                    Pages = 823,
                    ImageUrl = "2.jpg"

                },

                new Book() {
                    Id = 2,
                    Name = "Pet Sematary",
                    Author = "Stephen King",
                    Description = "Pet Sematary is a 1983 horror novel by American writer Stephen King. The novel was nominated for a World Fantasy Award for Best Novel in 1986,[1] and adapted into two films: one in 1989 and another in 2019. In November 2013, PS Publishing released Pet Sematary in a limited 30th-anniversary edition.[2]",
                    Pages = 373,
                    ImageUrl = "3.jpg"

                },

                new Book() {
                    Id = 3,
                    Name = "Salem's Lot",
                    Author = "Stephen King",
                    Description = "'Salem's Lot is a 1975 horror novel by American author Stephen King. It was his second published novel. The story involves a writer named Ben Mears who returns to the town of Jerusalem's Lot (or 'Salem's Lot for short) in Maine, where he lived from the age of five through nine, only to discover that the residents are becoming vampires. ",
                    Pages = 439,
                    ImageUrl = "4.jpg"

                }

            };
        }

        public static List<Book> Books {
            get {
                return _books;
            }
        }
        

        public static void AddBook(Book entity){
            _books.Add(entity);
        }

        public static Book GetById(int id){
            return _books.FirstOrDefault(i => i.Id == id);
        }
    }
}

Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace ChooseBookApp.Controllers
{
    public class BookController:Controller
    {
        public IActionResult Index()
        {
          //TODO: Implement Realistic Implementation
          return View();
        }
        public IActionResult Create()
        {
          //TODO: Implement Realistic Implementation
          return View();
        }
        public IActionResult Details()
        {
          //TODO: Implement Realistic Implementation
          return View();
        }
        public IActionResult List()
        {
          //TODO: Implement Realistic Implementation
          return View();
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ChooseBookApp.Models;
using ChooseBookApp.Data;



namespace ChooseBookApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index(int? id)
        {
            var books = BookRepository.Books;
            if(id != null) {
                books = books.Where( i => i.CategoryId == id).ToList();
            }

            return View(books);
        }
        
        public IActionResult Details(int id)
        {
           
          
          return View(BookRepository.GetById(id));
        }

        [Route("/privacy")]
        public IActionResult Privacy()
        {
            return View();
        }
        [Route("/contact")]
        public IActionResult Contact()
        {
          //TODO: Implement Realistic Implementation
          return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ViewComponents/CategoryMenuViewComponent.cs
using ChooseBookApp.Data;
using Microsoft.AspNetCore.Mvc;

namespace ChooseBookApp.ViewComponents
{
    public class CategoryMenuViewComponent:ViewComponent
    {

        public IViewComponentResult Invoke(){
            ViewBag.SelectedCategory = RouteData?.Values["id"];
            return View(CategoryRepository.Categories);
        }
        
    }
}

Views/Book/Details.cshtml
<h1>Book/Details</h1>

Views/Book/Index.cshtml
<h1>Book/Index</h1>

Views/Book/List.cshtml
<h1>Book/List</h1>

Views/Home/Contact.cshtml
<h1>Home/Contact</h1>

Views/Home/Details.cshtml
@model Book


<div class="row">
    <div class="col-md-3">
       
        @await Component.InvokeAsync("CategoryMenu")
    </div>
    <div class="col-md-9">
        <div class="card-body">
            <div class="row no-gutter">
                <div class="card mb-3">

                    <div class="col-md-3">
                        <img src="~/img/@Model.ImageUrl" alt="" class="card-img">

                    </div>
                    <div class="col-md-9">

                        <h5 class="card-title">
                            <a asp-action="Details" asp-controller="Home" asp-route-id="@Model.Id">@Model.Name</a>
                        </h5>
                        <h5 class="card-title">
                            @Model.Author
                        </h5>
                        <p class="card-text">
                            @Model.Description
                        </p>
                        <p class="card-text">
                            @Model.Pages
                        </p>
                        <p class="card-text">
                            <small class="text-muted">
                                3 days ago
                            </small>
                        </p>

                    </div>
                </div>



            </div>

        </div>

    </div>

</div>

Views/Home/Index.cshtml
@model IEnumerable<Book>;


<div class="row">
    <div class="col-md-3">
       
        @await Component.InvokeAsync("CategoryMenu")
    </div>
    <div class="col-md-9">
        @Html.Partial("_books",Model)
    </div>

</div>

Views/Home/_books.cshtml
@model IEnumerable<Book>

@foreach (var book in Model)
{
    <div class="card mb-3">
        <div class="row no-gutter">
            <div class="col-md-3">
                <img src="~/img/@book.ImageUrl" alt="" class="card-img">

            </div>
            <div class="col-md-9">
                <div class="card-body">
                    <h5 class="card-title">
                        <a asp-action="Details" asp-controller="Home" asp-route-id="@book.Id">@book.Name</a> 
                    </h5>
                    <h5 class="card-title">
                        @book.Author
                    </h5>
                    <p class="card-text">
                        @book.ShortDescription
                    </p>
                    <p class="card-text">
                        @book.Pages
                    </p>
                    <p class="card-text">
                        <small class="text-muted">
                            3 days ago
                        </small>
                    </p>

                </div>
            </div>
        </div>
    </div>

}

Views/Shared/Components/CategoryMenu/Default.cshtml
@model IEnumerable<Category>

<div class="list-group">

    @foreach (var i in Model)
    {
        <a asp-controller="Home" 
        asp-action="Index"
        asp-route-id = "@i.Id" 
        class="list-group-item list-group-item-action  @(ViewBag.SelectedCategory == i.Id.ToString()?"active":" ")">
        @i.Name
        </a>
        
    }

  

</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="/modules/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="/css/style.css" />
    <title>@ViewData["Title"] - BookApp</title>
    
    
</head>
<body>
    <header>
        @Html.Partial("_navbar")  
    </header>
    
        <main>
            <div class="container mt-4">
                @RenderBody()
            </div>
        </main>
    
    <footer >
       @Html.Partial("_footer")
    </footer>
    
</body>
</html>

Views/Shared/_footer.cshtml
<div class="footer py-3 mt-3">
    <div class="container">
        <span class="text-muted">
            Place Footer Content Here
        </span>
    </div>
</div>

Views/Shared/_menu.cshtml
@model IEnumerable<Category>

<div class="list-group">

    @foreach (var i in Model)
    {
        <a href="#" class="list-group-item list-group-item-action">@i.Name</a>
        
    }



    

</div>

Views/Shared/_navbar.cshtml
<div class="navbar navbar-expand-sm bg-primary navbar-dark">
    <div class="container">
        <a href="/" class="navbar-brand">Book App</a>
        <ul class="navbar-nav">
            <li class="nav-item">
                <a href="/login" class="nav-link">Login</a>
            </li>
            <li class="nav-item">
                <a href="/register" class="nav-link">Register</a>
            </li>
        </ul>
    </div>
</div>